spring.application.name=SpringSecurity
spring.datasource.url = jdbc:mysql://localhost:3306/SpringSecurity2
spring.datasource.username = root
spring.datasource.password = nishant123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true
jwt.secret=17o+Nf9ABQDeS8Ljx+0a6ZqNJyqXjx7DMfTi4hBuBAo=
jwt.issuer=Nishant
jwt.expiry=900
